name: Release workflows and actions

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version or major, minor, patch'
        default: 'patch'
        required: true

env:
  GH_BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_BOT_NAME: "GitHub Action"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Build the plugin
      - name: Build and Tag
        id: build
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name ${{ env.GH_BOT_NAME }}
          git config user.email ${{ env.GH_BOT_EMAIL }}

          npm ci
          npm build

          npm version ${INPUT_VERSION} --no-git-tag-version
          VERSION=$(grep '^  "version"' package.json | cut -d'"' -f4)
          echo $VERSION

          if git rev-parse "refs/tags/$VERSION" > /dev/null 2>&1; then
            echo "🛑 Tag $VERSION already exists"
            exit 1
          fi

          # Create a new branch for the release
          git checkout -b release/$VERSION

          # Update references from main to the new release branch
          sed -i 's|\(ref":\) "main"|\1 "release/'$VERSION'"|' .github/actions/count-votes/action.yml
          sed -i 's|\(ref":\) "main"|\1 "release/'$VERSION'"|' .github/workflows/receive-votes.yml

          git add .
          git status
          git commit -m "🔖 $VERSION"
          git push --set-upstream origin release/$VERSION

          git tag $VERSION
          git push --tags

          gh release create "$VERSION" \
              --title "Release $VERSION" \
              --verify-tag \
              --prerelease=${prerelease}

          gh release upload "$VERSION" --clobber \
            './dist/genIndex.js#genIndex.js' \
            './dist/votes.js#votes.js'
